project_id = "cyyrmlyubatbqvetwdpj"

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-sms-reminder]
verify_jwt = false

[functions.send-sms-reminder-scheduled]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.notify-waitlist]
verify_jwt = false
